package DynamicProgramming.oneDimension;

// https://leetcode.com/problems/ugly-number-ii/description/
public class UglyNumberII {
    public int nthUglyNumber(int n) {
        int[] ugly = new int[n];
        ugly[0] = 1;

        int p2 = 0, p3 = 0, p5 = 0; // pointers for 2, 3 and 5

        for (int i = 1; i < n; i++) {
            int next2 = ugly[p2] * 2; // the next ugly number generated by multiplying 2 with the last ugly number pointed by p2
            int next3 = ugly[p3] * 3;
            int next5 = ugly[p5] * 5;

            int next = Math.min(next2, Math.min(next3, next5)); // the next ugly number is the minimum of the three next ugly numbers generated by multiplying 2, 3 and 5 with the last ugly numbers pointed by p2, p3 and p5 respectively
            ugly[i] = next; // we store the next ugly number in the array

            if (next == next2) p2++; // if the next ugly number is generated by multiplying 2, we move the pointer for 2 to the next position
            if (next == next3) p3++;
            if (next == next5) p5++;
        }

        return ugly[n - 1]; // we return the nth ugly number which is stored at index n-1 in the array
    }
}
